version: "3.1"
services:
  config-server:
    build:
      config-server
    deploy:
      resources:
        limits:
          cpus: '0.5'	
          memory: 300M
        reservations:
          cpus: '0.3'	
          memory: 200M
  accounts-provider:
    build:
      accounts-provider
    deploy:
      resources:
        limits:
          cpus: '0.5'	
          memory: 300M
        reservations:
          cpus: '0.3'	
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}		  
  sensor-emails-provider:
    build:
      sensor-emails-provider
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M 
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
  sensor-range-provider:
    build:
      sensor-range-provider
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M 
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
  admin-console:
    build:
      admin-console
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - STREAM_API_PASSWORD=${STREAM_API_PASSWORD}
  analyzer:
    build:
      analyzer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_PASSWORD=${STREAM_API_PASSWORD}
  avg-populator:
    build:
      avg-populator
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - STREAM_API_PASSWORD=${STREAM_API_PASSWORD}
  avg-reducer:
    build:
      avg-reducer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_PASSWORD=${STREAM_API_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  email-notifier:
    build:
      email-notifier
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_PASSWORD=${STREAM_API_PASSWORD}
      - MAIL_TOKEN=${EMAIL_TOKEN}
  gateway:
    build:
      gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M 
    ports:
      - 8585:8585                              
